use_frameworks!
  
target 'shlack' do
pod 'RealmSwift'
pod 'YMTGetDeviceName'
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'SwiftyJSON'
pod 'FirebaseUI'
# https://firebase.google.com/docs/ios/setup#available-pods
end
